config/routes.rb
Rails.application.routes.draw do
  get 'invites/create'

  get 'invites/destroy'

	root 'static_pages#home'
	get '/signup', 		to: 'users#new'
	post '/signup',		to: 'users#create'
	get '/login', 		to: 'sessions#new'
	post '/login', 		to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'
	resources :users, only: [:new, :create, :show, :edit, :update]
	resources :events, only: [:new, :create, :show, :index]
	resources :invites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :host, class_name: "User"
	has_many :invites, foreign_key: "event_id", dependent: :destroy
	has_many :attendees, through: :invites, source: "attendee", dependent: :destroy
	validates :name, presence: true, length: { maximum: 40 }
	validates :description, presence: true, length: { minimum: 10 }
	validates :location, presence: true
	validates :date, presence: true
	validates :time, presence: true

	def self.upcoming
		self.where("date > ?", DateTime.now).order("date ASC")
	end

	def self.past
		self.where("date < ?", DateTime.now).order("date ASC")
	end
end

app/models/invite.rb
class Invite < ApplicationRecord
	belongs_to :attendee, class_name: "User"
	belongs_to :event, class_name: "Event"
	validates :event_id, presence: true
	validates :attendee_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
	has_many :hosted_events, foreign_key: "host_id", class_name: "Event", dependent: :destroy
	has_many :invites, foreign_key: "attendee_id", dependent: :destroy
	has_many :attended_events, through: :invites, source: "event", dependent: :destroy
	validates :name, presence: true, length: { maximum: 30 }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }


	def self.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def self.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated(token)
		BCrypt::Password.new(remember_digest).is_password?(token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def upcoming
		self.where("date > ?", DateTime.now).order("date ASC")
	end

	def past
		self.where("date < ?", DateTime.now).order("date ASC")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  include EventsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :check_for_sign_in, only: [:index, :show]

	def index
		if request.fullpath.include?('upcoming=true')
			@events = Event.upcoming
		elsif request.fullpath.include?('past=true')
			@events = Event.past
		else
			@events = Event.order('date DESC')
		end
	end

	def show
		@event = Event.find(params[:id])
		@attendees = @event.attendees
	end

	def new
		if current_user.nil?
			flash[:warning] = "Please log in to create an event"
			redirect_to login_path
		else
			@event = Event.new
		end
	end

	def create
		@event = current_user.hosted_events.build(event_params)
		if @event.save
			attend_hosted_event(@event)
			flash[:success] = "Event successfully created"
			redirect_to @event
		else
			flash.now[:warning] = "Invalid submission"
			render 'new'
		end
	end

	private

		# Whitelists certain parameters to be used for assignment.
		def event_params
			params.require(:event).permit(:name, :description, :location, :date, :time)
		end

		def check_for_sign_in
			redirect_to root_url if current_user.nil?
		end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
  	current_user.invites.create(event_id: params[:invite][:event_id])
		redirect_back(fallback_location: root_url)
  end

  def destroy
  	@invite = current_user.invites.find_by(event_id: params[:id])
  	current_user.invites.destroy(@invite.id)
  	redirect_back(fallback_location: root_url)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(name: params[:session][:name])
		if @user && @user.authenticate(params[:session][:password])
			log_in @user
			params[:session][:remember_me] == 1 ? remember(@user) : forget(@user)
			flash[:success] = "Logged in successfully"
			redirect_to @user
		else
			flash.now[:warning] = "Wrong name and/or password"
			render 'new'
		end
	end

	def destroy
		log_out if logged_in?
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:edit, :update]

	def show
		@user = User.find(params[:id])
		if request.fullpath.include?('host_upcoming=true')
			@events = @user.hosted_events.upcoming
		elsif request.fullpath.include?('host_past=true')
			@events = @user.hosted_events.past
		elsif request.fullpath.include?('attend_upcoming=true')
			@events = @user.attended_events.upcoming
		elsif request.fullpath.include?('attend_past=true')
			@events = @user.attended_events.past
		else 
			@events = @user.hosted_events
		end
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Registered successfully."
			redirect_to root_url
		else
			flash.now[:warning] = "Invalid information"
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			flash[:success] = "Profile updated."
			redirect_to @user
		else
			flash.now[:warning] = "Invalid information"
			render 'edit'
		end
	end

	private

		# Whitelists certain parameters to be used for mass assignment.
		def user_params
			params.require(:user).permit(:name, :password, :password_confirmation)
		end

		# Checks whether the logged in user is the same as the user page requested.
		def correct_user
			@user = User.find(params[:id])
			redirect_to root_url unless @user == current_user
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	#Returns a full title on a per-page basis.
	def full_title(page_title = '')
		base_title = "Private events"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
end

app/helpers/events_helper.rb
module EventsHelper

	# Makes the user creating the event automatically an attendee.
	def attend_hosted_event(event)
		current_user.invites.create(event_id: event.id)
	end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Sets a session cookie for the user that logs in.
	def log_in(user)
		session[:user_id] = user.id
	end

	# Adds a remember token in digest form to the database and creates two cookies for the user that logs in.
	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	# Returns the current logged in user.
	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	# Calls the current_user method above to check for a logged in user.
	def logged_in?
		!current_user.nil?
	end

	# Deletes the rember token digest from the database and both cookies.
	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	# Calls the forget method above, deletes the session cookie and sets the current user instance variable to nil.
	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<% provide(:title, "All events") %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="btn-group btn-group-justified">
			<%= link_to "Upcoming events", events_path(upcoming: true), class: 'btn btn-info btn-small' %>
			<%= link_to "Past events", events_path(past: true), class: 'btn btn-info btn-small' %>
		</div>
		<% if @events.any? %>
			<% @events.each do |event| %>
				<div class="result content-div">
					<ul class="text-center">
						<li><h2><%= link_to event.name, event %></h2></li>
						<hr>
						<li>Description: <%= event.description %></li>
						<li>Location: <%= event.location %></li>
						<li>Date: <%= event.date.strftime("%d-%m-%Y") %></li>
						<li>Time: <%= event.time.strftime("%H:%M") %></li>
						<li>Hosted by: <%= event.host.name %></li>
					</ul>
				</div>
			<% end %>
		<% else %>
			<div class="result content-div">
				<ul class="text-center">
					<li><h2 class="text-center">No events</h2></li>
				</ul>
			</div>
		<% end %>
	</div>
</div>

app/views/events/new.html.erb
<% provide(:title, "Create event") %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="content-div">
			<h2>Create a new event</h2>
			<%= form_for(@event, url: events_path) do |f| %>
			
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
			
				<%= f.label :description %>
				<%= f.text_area :description, class: 'form-control' %>
			
				<%= f.label :location %>
				<%= f.text_field :location, class: 'form-control' %>
			
				<%= f.label :date %>
				<%= f.date_field :date, class: 'form-control' %>
			
				<%= f.label :time %>
				<%= f.time_field :time, class: 'form-control' %>
				<br>
				<%= f.submit "Create event", class: 'btn btn-primary center-block' %>
			<% end %>
		</div>
	</div>
</div>

app/views/events/show.html.erb
<% provide(:title, @event.name) %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="result content-div">
			<ul class="text-center">
				<li><h2><%= @event.name %></h2></li>
				<hr>
				<li>Description: <%= @event.description %></li>
				<li>Location: <%= @event.location %></li>
				<li>Date: <%= @event.date.strftime("%d-%m-%Y") %></li>
				<li>Time: <%= @event.time.strftime("%H:%M") %></li>
			</ul>
				<% if @event.date < DateTime.now %>
					<p>This event has already taken place.</p>
				<% elsif @event.attendees.include?(current_user) %>
					<%= form_for(:invite, url: invite_path, html: { method: :delete }) do |f| %>
						<%= f.submit "Leave event", class: 'center-block btn btn-danger' %>
					<% end %>
				<% else %>
					<%= form_for(:invite, url: invites_path) do |f| %>
						<%= f.hidden_field :event_id, value: @event.id %>
						<%= f.submit 'Attend event', class: 'center-block btn btn-success' %>
					<% end %>
				<% end %>
		</div>
		<div class="result content-div">
			<ul class="text-center">
				<li><h2>Attendees</h2></li>
				<hr>
				<% if @attendees.any? %>
					<% @attendees.each do |attendee| %>
						<li><%= link_to attendee.name, attendee %></li>
					<% end %>
				<% else %>
					<li>No attendees</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/invites/create.html.erb
<h1>Invites#create</h1>
<p>Find me in app/views/invites/create.html.erb</p>

app/views/invites/destroy.html.erb
<h1>Invites#destroy</h1>
<p>Find me in app/views/invites/destroy.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-left">
				<li><a href="https://tomwesterhout.github.io"><i class="glyphicon glyphicon-modal-window"></i> Portfolio</a></li>
				<li><a href="https://github.com/tomwesterhout">Github</a></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header>
	<div class="container">
		<nav>
			<ul class="nav navbar-nav navbar-left">
				<li><%= link_to "Private Events", root_path, id: "logo" %></li>
			</ul>
		</nav>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li>
					<%= link_to root_url do %>
						<i class="glyphicon glyphicon-home"></i> Home
					<% end %>
				</li>
				<% if logged_in? %>
					<li>
						<%= link_to events_path do %>
							<i class="glyphicon glyphicon-list-alt"></i> Events
						<% end %>
					</li>
					<li>
						<%= link_to new_event_path do %>
							<i class="glyphicon glyphicon-plus"></i> Create event
						<% end %>
					</li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">  <i class="glyphicon glyphicon-user"></i>
							<%= current_user.name %><b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li><%= link_to "Log out", logout_path, method: 'delete' %></li>
						</ul>
					</li>
				<% else %>
					<li>
						<%= link_to login_path do %>
							<i class="glyphicon glyphicon-user"></i> Log in
						<% end %>
					</li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
  	<div class="content">
      <div class="jumbotron">
        <div class="text-center col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
          <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{ message_type}") %>
          <% end %>
        </div>
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="row home">
<h1>Welcome to Private Events</h1>
<br>
<div class="button-center">
	<% if logged_in? %>
		<%= link_to "Create event", new_event_path, class: 'btn btn-lg btn-primary' %>
	<% else %>
		<%= link_to "Sign up", signup_path, class: 'btn btn-lg btn-primary' %>
	<% end %>
</div>
</div>

app/views/users/edit.html.erb
<% provide(:title, "Settings") %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="content-div">
			<h2>Account settings</h2>
			<%= form_for(@user, url: user_path) do |f| %>
	
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
	
				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>
	
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>
				<br>
				<%= f.submit "Save changes", class: 'btn btn-primary center-block' %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/new.html.erb
<% provide(:title, "Signup") %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="content-div">
			<h2>Sign up</h2>
			<%= form_for(@user, url: signup_path) do |f| %>
				
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control' %>
				
				<%= f.label :password %>
				<%= f.password_field :password, class: 'form-control' %>
				
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: 'form-control' %>
				<br>
				<%= f.submit 'Create', class: 'btn btn-primary center-block' %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<div class="col-xs-12 col-xs-offset-0 col-sm-8 col-sm-offset-2 col-md-8 col-md-offset-2">
		<div class="btn-group btn-group-justified">
			<%= link_to "Hosted upcoming events", user_path(current_user, host_upcoming: true), class: 'btn btn-info btn-small' %>
			<%= link_to "Hosted past events", user_path(current_user, host_past: true), class: 'btn btn-info btn-small' %>
			<%= link_to "Attended upcoming events", user_path(current_user, attend_upcoming: true), class: 'btn btn-info btn-small' %>
			<%= link_to "Attended past events", user_path(current_user, attend_past: true), class: 'btn btn-info btn-small' %>
		</div>
		<% if @events.any? %>
			<% @events.each do |event| %>
				<div class="result content-div">
					<ul class="text-center">
						<li><h2><%= link_to event.name, event %></h2></li>
						<hr>
						<li>Description: <%= event.name %></li>
						<li>Location: <%= event.description %></li>
						<li>Date: <%= event.date.strftime("%d-%m-%Y") %></li>
						<li>Time: <%= event.time.strftime("%H:%M") %></li>
					</ul>
				</div>
			<% end %>
		<% else %>
			<div class="result content-div">
				<ul class="text-center">
					<li><h2>No events</h2></li>
				</ul>
			</div>
		<% end %>
	</div>
</div>